settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('validador.urls'))
]

validador/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("validadorxml", views.validadorxml, name="validadorxml")
]

validador/models.py
from django.db import models

# Create your models here.

validador/forms.py
from django import forms
from django.core.validators import FileExtensionValidator as FEV


class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='CLIQUE PARA INSERIR O ARQUIVO',
        validators=[FEV(['xml'], u'Utilizar apenas extensão XML', '001')]
    )

validador/views.py
# import xml.etree.ElementTree as ET
from lxml import etree as ET
from django.shortcuts import render
import validador.rulesXML as rules
from .forms import UploadFileForm
from datetime import datetime
import re

def validadorxml(request, infor):
    return render(request, "validador/validadorxml.html", infor)


def index(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES["file"]
            errors = []
            for message in rules.validate_schema(f):
                errors.append(message)
            f.seek(0)
            file = ET.parse(f)
            root = file.getroot()

            nsNFE = {
                'ns': "http://www.portalfiscal.inf.br/nfe"
            }
            caminho = rules.best_way(file)

            modelo_nfe = root.find(caminho + 'ns:ide/ns:mod', nsNFE)
            # VALIDAÇÃO DO TIPO DE NOTA FISCAL
            infor = rules.type_nota(file, caminho, modelo_nfe)
            infor['metodo'] = request.method
            infor['form'] = form
            infor['errors'] = errors
            return render(request, "validador/validadorxml.html", infor)
    else:
        form = UploadFileForm()
    return render(request, "validador/index.html", {"form": form, "metodo": request.method})

templates/validador/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="icon" type="image/png" href="{% static 'image/xml.png' %}"/>

        <title>XML Validator</title>
    </head>
    <body>
        <div class="conteiner_Principal">
            <div class="conteiner_interno">
                <div class="tittle_XML">
                        <h1>VALIDADOR XML</h1>
                </div>
                <form class="conteiner_form" method="post" enctype="multipart/form-data">
                    <div>
                        {% csrf_token %}
                        <label for="id_file" class="button" id="envir_arquivo" >Selecione um arquivo XML</label>
                        <input type="file" name="file" required id="id_file">
                        <input class="button_enviar" type="submit" value="Enviar arquivo"></input>
                
                      </div>
                </form>
            </div>
        </div>
    </body>
</html>

templates/validador/validadorxml.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Validador</title>
        <link rel="stylesheet" href="{% static 'css/style_validador.css' %}">
        <link rel="icon" type="image/png" href="{% static 'image/xml.png' %}"/>

        <script>
            function error_info(){
                var erro = document.querySelector('.textInfo');
                erro.innerHTML='' + '<p> {{ erro_pagamento }} <br> {{ alq_validado }} </p>'
            }

            function product_info(){
                var prod= document.querySelector('.textInfo');
                prod.innerHTML='' +
                    '{% for produto in produtos %}' +
                    '<p> <strong> Nome: </strong> {{ produto.nome }} <strong> Código: </strong> {{ produto.codigo }}</p>'+
                    '<p> <strong> Valor Unitário: </strong> R$ {{ produto.valor_unitario }} <strong> Quantidade: </strong> {{ produto.quantidade }} <strong> Valor Total: </strong> R$ {{ produto.valor_total }}</p>'+
                    '<br>'+
                    '{% endfor %}'
            }

            function info_nf(){
                var info = document.querySelector('.textInfo');
                info.innerHTML='' + '<p> <strong> Data-Hora Emissão: </strong> {{ data }} ' +
                    '<p> <strong> Natureza da Operação: </strong> {{ op }} </p>' +
                    '<p> <strong> Tributos: </strong> {{ infcpl }} </p>'
            }

            function info(){
                var info = document.querySelector('.textInfo');
                info.innerHTML='' + ' <div>'+
               ' <div>'+
                 '<br>'+
                    '<p> <strong> Chave de Acesso da Nota: </strong> {{ Chave_de_Acesso }} </p>'+
                   ' <p> <strong> Número da Nota:</strong> {{ Numero_da_Nota }} <strong>Série:</strong> {{ Serie }} <strong>Modelo:</strong> {{ modelo }}</p>'+
                   ' <p> <strong> Emitente: </strong> {{ Emitente }} </p>'+
                   ' <p> <strong> CNPJ do Emitente: </strong> {{ CNPJ_Emitente }} </p>'+
                    '<p> <strong> Destinatário: </strong> {{ dest_name }} </p>'+
                   ' {% if cnpj_cpf_dest_len > 14 %}'
                  '  <p> <strong> CNPJ do Destinatário: </strong> {{ cnpj_cpf_dest }} </p>'+
                   ' {% else %}'+
                  '  <p> <strong> CPF do Destinatário: </strong> {{ cnpj_cpf_dest }} </p>'+
                  '  {% endif %}'+
                   ' <br>'+
              '  </div>'+
        ' </div>'
            }
            function xml(){
                var info = document.querySelector('.textInfo');
                info.innerHTML='' + ' <pre>{{ xml }}</pre> '
            }
            
        </script>
    </head>
    <body>
        <p class="tittle"> VALIDADOR DE XMLs</p>
<div class="conteiner_P">
   
    <form class="conteiner_form" method="post" enctype="multipart/form-data">
        <div>
            {% csrf_token %}
                <label for="id_file" class="button" id="envir_arquivo" >Selecione um arquivo XML</label>
                <input type="file" name="file" required id="id_file">
                <input class="button_enviar" type="submit" value="Enviar arquivo"></input>
                
        </div>
    </form>
</div>   

    <div class="divButton">
        <button class="button-7" role="button" onclick="error_info()" > Erros </button>
        <button class="button-7" role="button" onclick="product_info()" > Produtos </button>
        <button class="button-7" role="button" onclick="info_nf()" > Geral </button>
        <button class="button-7" role="button" onclick="info()">Informações</button>
        <button class="button-7" role="button" onclick="xml()">XML</button>
    </div>
<div class="xml">
        {% if metodo == 'POST' %}
            <div class="mostraXML" id="xml">
                <div class="textInfo">
                    <pre>{{ xml }}</pre>
                </div>
            </div>
        {% endif %}
</div>

    </body>
</html>